sudo: false

addons:
  apt:
    packages:
      - netpbm
      - x11-apps
      - ffmpeg
      - unzip
      # - chromium-browser
  artifacts:
    paths:
      - ./out.mpg
      - ./screen1.xwd
      # - ./screen2.xwd
      # - ./screen3.xwd
      # - ./screen4.xwd
      # - ./screen5.xwd
      # - ./screen6.xwd
     # - ./screen7.xwd

language: node_js

node_js:
  - 0.12

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_98.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :98 -ac -screen 0 1280x1024x16"
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq netpbm x11-apps

install:
  # - npm install
  # - npm install -g cypress

before_script:
  - "export DISPLAY=:98"

script:
  # - http-server -p 6060 &
  # - cypress ci &
  # - cypress install
  # - /home/travis/.cypress/Cypress/Cypress --ci --key=9f697026-c394-4814-8ce9-0248b5f77c69 --project=/home/travis/build/brian-mann/lancelotapp2 &
  # - "chromium-browser --no-sandbox http://5074da32.ngrok.io/__/#/tests/03-logedout-order.js &"
  - wget https://s3.amazonaws.com/artifacts.cypress.io/chromium-49.zip
  - unzip chromium-49.zip
  - "./chrome-linux/chrome --no-sandbox --ignore-certificate-errors --window-size=1280,720 http://199e5ba7.ngrok.io/__#/tests/03-logedout-order.js &"
  - ffmpeg -y -r 30 -g 300 -t 60 -f x11grab -s 1280x1024 -i :98 out.mpg &
  # - sed -i 's/\r//' ./node_modules/nw/bin/nw
  # - sleep 4
  - sleep 65
  - xwd -root -silent -display :98  > screen1.xwd