sudo: false

addons:
  apt:
    packages:
      - netpbm
      - x11-apps
      - ffmpeg
      - chromium-browser
  artifacts:
    paths:
      - ./out.mpg
      - ./screen1.xwd
      # - ./screen2.xwd
      # - ./screen3.xwd
      # - ./screen4.xwd
      # - ./screen5.xwd
      # - ./screen6.xwd
     # - ./screen7.xwd

language: node_js

node_js:
  - 0.12

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_98.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :98 -ac -screen 0 1280x1024x16"
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq netpbm x11-apps

# install:
  # - npm install
  # - npm install -g cypress

before_script:
  - "export DISPLAY=:98"

script:
  # - http-server -p 6060 &
  # - cypress ci &
  # - cypress install
  # - /home/travis/.cypress/Cypress/Cypress --ci --key=9f697026-c394-4814-8ce9-0248b5f77c69 --project=/home/travis/build/brian-mann/lancelotapp2 &
  - "chromium-browser --no-sandbox http://5074da32.ngrok.io/__/#/tests/__all &"
  - sleep 4
  - ffmpeg -y -r 30 -g 300 -t 120 -f x11grab -s 1280x1024 -i :98 out.mpg &
  - sleep 125
  - xwd -root -silent -display :98  > screen1.xwd