sudo: false

addons:
  apt:
    packages:
      - netpbm
      - x11-apps
      - ffmpeg
  artifacts:
    paths:
      - ./out.mpg
      - ./screen1.xwd
      - ./screen2.xwd
      - ./screen3.xwd
      - ./screen4.xwd
      - ./screen5.xwd
      - ./screen6.xwd
     # - ./screen7.xwd

language: node_js

node_js:
  - 0.12

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_98.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :98 -ac -screen 0 1280x1024x16"
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq netpbm x11-apps

install:
  # - npm install
  - npm install -g cypress

before_script:
  - "export DISPLAY=:98"

script:
  - ps aux --sort -rss
  - free -m
  # - http-server -p 6060 &
  # - cypress ci &
  - cypress ci &
  - /home/travis/.cypress/Cypress/Cypress --ci --key=9f697026-c394-4814-8ce9-0248b5f77c69 --project=/home/travis/build/brian-mann/lancelotapp2 &
  - sleep 5
  - xwd -root -silent -display :98  > screen1.xwd
  - ffmpeg -y -r 30 -g 300 -f x11grab -s 1024x768 -i :98 out.mpg &
  - sleep 10
  - xwd -root -silent -display :98  > screen2.xwd
  - ps aux --sort -rss
  - free -m
  - sleep 10
  - xwd -root -silent -display :98  > screen3.xwd
  - ps aux --sort -rss
  - free -m
  - sleep 10
  - xwd -root -silent -display :98  > screen4.xwd
  - ps aux --sort -rss
  - free -m
  - sleep 10
  - xwd -root -silent -display :98  > screen5.xwd
  - ps aux --sort -rss
  - free -m
  - sleep 10
  - xwd -root -silent -display :98  > screen6.xwd
  - ps aux --sort -rss
  - free -m